# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

# create function locally
# https://docs.microsoft.com/en-us/java/api/overview/azure/maven/azure-functions-maven-plugin/readme?view=azure-java-stable#goals
- task: Bash@3
  inputs:
    targetType: 'inline'
    #filePath: # Required when targetType == FilePath
    #arguments: # Optional
    script: |
      mvn package
    #workingDirectory: # Optional
    #failOnStderr: false # Optional- task: 

# Archive Files
# Archive files using compression formats such as .7z, .rar, .tar.gz, and .zip.
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: target/azure-functions/portal-lexnet
    includeRootFolder: false
    #archiveType: 'zip' # Options: zip, 7z, tar, wim
    #tarCompression: 'gz' # Optional. Options: gz, bz2, xz, none
    #archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip' 
    #replaceExistingArchive: true 
    #verbose: # Optional
    #quiet: # Optional
    
# Publish Pipeline Artifact
# Publish a local directory or file as a named artifact for the current pipeline.
# - task: PublishPipelineArtifact@0
#  inputs:
#    # 'drop' is default name for artifacts
#    # artifactName: 'drop' 
#    targetPath: $(Build.ArtifactStagingDirectory)

# Release can't find produced artifacts
# https://developercommunity.visualstudio.com/content/problem/349729/error-no-package-found-with-specified-pattern-dar1.html
- task: PublishBuildArtifacts@1
   # 'drop' is default name for artifacts

