# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

# Currently, Microsoft-hosted agents do not have the AZ CLI installed. You can either install it using npm install -g azure-cli (on Microsoft-hosted Linux agents, use sudo npm install -g azure-cli) or use a self-hosted agent with the AZ CLI pre-installed.
# https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-cli?view=azure-devops#arguments
# Bash
# Run a Bash script on macOS, Linux, or Windows
- task: Bash@3
  inputs:
    targetType: 'inline'
    #filePath: # Required when targetType == FilePath
    #arguments: # Optional
    script: |
      npm install -g azure-cli
    #workingDirectory: # Optional
    #failOnStderr: false # Optional- task: 
      

# Azure CLI
# Run Azure CLI commands against an Azure subscription in a Shell script when runnning on Linux agent or Batch script when running on Windows agent.
- task: AzureCLI@1
  inputs:
    azureSubscription: giolegal-devops-connection
    scriptLocation: 'inlineScript'
    inlineScript: | # Required when scriptLocation == InlineScript
      mvn azure-functions:deploy
    #arguments: # Optional
    #addSpnToEnvironment: false # Optional
    #useGlobalConfig: false # Optional
    #workingDirectory: # Optional
    #failOnStandardError: false # Optional